/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  IToggleOptions,
} from './utils/interface';

export namespace Components {
  interface HomeAbout {
    'toggleOptions': IToggleOptions;
  }
}

declare global {


  interface HTMLHomeAboutElement extends Components.HomeAbout, HTMLStencilElement {}
  var HTMLHomeAboutElement: {
    prototype: HTMLHomeAboutElement;
    new (): HTMLHomeAboutElement;
  };
  interface HTMLElementTagNameMap {
    'home-about': HTMLHomeAboutElement;
  }
}

declare namespace LocalJSX {
  interface HomeAbout extends JSXBase.HTMLAttributes<HTMLHomeAboutElement> {
    'toggleOptions'?: IToggleOptions;
  }

  interface IntrinsicElements {
    'home-about': HomeAbout;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


